### ISSUE TITLE
No map visible. Javascript errors

### ISSUE THREAD

**Issue by tknuppe** [ollietb/OhGoogleMapFormTypeBundle#26]
Hi
I'm trying to add the Input Field to a sonata Admin (inside a Tab) (. I followed the instructions in the readme. The Input fields are rendered but there is no map.

A Javascript error occurs:
TypeError: $(...).ohGoogleMapType is not a function
error source line:
$('#s55adff382b3a8_latlng_map_canvas').ohGoogleMapType({

symfony/symfony                            v2.6.9
sonata-project/admin-bundle                2.3.3

jquery#2.1.3

**Comment by ollietb** [comment]
@tknuppe You will have to include the javascript file manually
